### ISSUE TITLE
MOTD improvements

### ISSUE THREAD

**Issue by deepend-tildeclub** [tildeclub/motd#1]
Think its time to improve the readability of the MOTD on tilde.club.  Shorten it down without loosing all of its charm.

**Comment by deepend-tildeclub** [comment]
@audiodude   Just thought i'd ping you in case you didn't realize this repo exists :D  

Thanks

**Comment by audiodude** [comment]
I'm definitely interested in giving it a pass.

One thing is that I'd like to use ANSI codes to bold keywords that can be used in the wiki. Do you by any chance know how I'd add them to the copy on github? I can add them in emacs, just wondering if they'll translate.

**Comment by deepend-tildeclub** [comment]
Not sure.. Add them in emacs and push them to github and see what shows 
in the file on github maybe?
